// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfqoaievmuheaxmcqthp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmcW9haWV2bXVoZWF4bWNxdGhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzNjQyMTIsImV4cCI6MjA1Mzk0MDIxMn0.u223EFIi_3tA4tQIAQwRzmhtbhOiaNlutW1MRrZd908";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);